### ISSUE TITLE
Translate OCL to Plugin description for Huawei Cloud

### ISSUE THREAD

**Issue by niuzhenguo** [huaweicloud/osc#23]
## Task List

* [ ] Translate image block to Packer description.
* [ ] Translate vm block to Terraform description.
* [ ] Translate network block to Terraform description.
* [ ] Translate storage block to Terraform description.
